env:
  browser: true
  es6: true
  mocha: true
  commonjs: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent: 0
  linebreak-style:
    - error
    - unix
  quotes: 0
  semi: 0
  no-unused-vars: 0
  no-async-promise-executor: off
  react/prop-types: off
  react/display-name: off
  react/jsx-key: off
