// source: activity_log.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var user_pb = require('./user_pb.js');
goog.object.extend(proto, user_pb);
goog.exportSymbol('proto.ActivityLog', null, global);
goog.exportSymbol('proto.ActivityLogList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ActivityLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ActivityLog.repeatedFields_, null);
};
goog.inherits(proto.ActivityLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ActivityLog.displayName = 'proto.ActivityLog';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ActivityLogList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ActivityLogList.repeatedFields_, null);
};
goog.inherits(proto.ActivityLogList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ActivityLogList.displayName = 'proto.ActivityLogList';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ActivityLog.repeatedFields_ = [13,17,22];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ActivityLog.prototype.toObject = function(opt_includeInstance) {
  return proto.ActivityLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ActivityLog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ActivityLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    userId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    activityName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    activityDate: jspb.Message.getFieldWithDefault(msg, 4, ""),
    propertyId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    contractId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    geolocationLat: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    geolocationLng: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    customerId: jspb.Message.getFieldWithDefault(msg, 9, 0),
    taskId: jspb.Message.getFieldWithDefault(msg, 10, 0),
    timesheetLineId: jspb.Message.getFieldWithDefault(msg, 11, 0),
    eventId: jspb.Message.getFieldWithDefault(msg, 12, 0),
    fieldMaskList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    pageNumber: jspb.Message.getFieldWithDefault(msg, 14, 0),
    orderBy: jspb.Message.getFieldWithDefault(msg, 15, ""),
    orderDir: jspb.Message.getFieldWithDefault(msg, 16, ""),
    dateRangeList: (f = jspb.Message.getRepeatedField(msg, 17)) == null ? undefined : f,
    withUser: jspb.Message.getBooleanFieldWithDefault(msg, 18, false),
    user: (f = msg.getUser()) && user_pb.User.toObject(includeInstance, f),
    timeoffRequestId: jspb.Message.getFieldWithDefault(msg, 20, 0),
    dateTarget: jspb.Message.getFieldWithDefault(msg, 21, ""),
    notEqualsList: (f = jspb.Message.getRepeatedField(msg, 22)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ActivityLog}
 */
proto.ActivityLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ActivityLog;
  return proto.ActivityLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ActivityLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ActivityLog}
 */
proto.ActivityLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUserId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setActivityName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setActivityDate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPropertyId(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setContractId(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGeolocationLat(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGeolocationLng(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCustomerId(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTaskId(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimesheetLineId(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEventId(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addFieldMask(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageNumber(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderBy(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderDir(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.addDateRange(value);
      break;
    case 18:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWithUser(value);
      break;
    case 19:
      var value = new user_pb.User;
      reader.readMessage(value,user_pb.User.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimeoffRequestId(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setDateTarget(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.addNotEquals(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ActivityLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ActivityLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ActivityLog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ActivityLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getUserId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getActivityName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getActivityDate();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPropertyId();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getContractId();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getGeolocationLat();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getGeolocationLng();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getCustomerId();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getTaskId();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getTimesheetLineId();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getEventId();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getFieldMaskList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getPageNumber();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getOrderBy();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getOrderDir();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getDateRangeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      17,
      f
    );
  }
  f = message.getWithUser();
  if (f) {
    writer.writeBool(
      18,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      user_pb.User.serializeBinaryToWriter
    );
  }
  f = message.getTimeoffRequestId();
  if (f !== 0) {
    writer.writeInt32(
      20,
      f
    );
  }
  f = message.getDateTarget();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getNotEqualsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      22,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.ActivityLog.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 user_id = 2;
 * @return {number}
 */
proto.ActivityLog.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setUserId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string activity_name = 3;
 * @return {string}
 */
proto.ActivityLog.prototype.getActivityName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setActivityName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string activity_date = 4;
 * @return {string}
 */
proto.ActivityLog.prototype.getActivityDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setActivityDate = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 property_id = 5;
 * @return {number}
 */
proto.ActivityLog.prototype.getPropertyId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setPropertyId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 contract_id = 6;
 * @return {number}
 */
proto.ActivityLog.prototype.getContractId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setContractId = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional double geolocation_lat = 7;
 * @return {number}
 */
proto.ActivityLog.prototype.getGeolocationLat = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setGeolocationLat = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional double geolocation_lng = 8;
 * @return {number}
 */
proto.ActivityLog.prototype.getGeolocationLng = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setGeolocationLng = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional int32 customer_id = 9;
 * @return {number}
 */
proto.ActivityLog.prototype.getCustomerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setCustomerId = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 task_id = 10;
 * @return {number}
 */
proto.ActivityLog.prototype.getTaskId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setTaskId = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 timesheet_line_id = 11;
 * @return {number}
 */
proto.ActivityLog.prototype.getTimesheetLineId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setTimesheetLineId = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 event_id = 12;
 * @return {number}
 */
proto.ActivityLog.prototype.getEventId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setEventId = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * repeated string field_mask = 13;
 * @return {!Array<string>}
 */
proto.ActivityLog.prototype.getFieldMaskList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setFieldMaskList = function(value) {
  return jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.addFieldMask = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.clearFieldMaskList = function() {
  return this.setFieldMaskList([]);
};


/**
 * optional int32 page_number = 14;
 * @return {number}
 */
proto.ActivityLog.prototype.getPageNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setPageNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional string order_by = 15;
 * @return {string}
 */
proto.ActivityLog.prototype.getOrderBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setOrderBy = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string order_dir = 16;
 * @return {string}
 */
proto.ActivityLog.prototype.getOrderDir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setOrderDir = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * repeated string date_range = 17;
 * @return {!Array<string>}
 */
proto.ActivityLog.prototype.getDateRangeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 17));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setDateRangeList = function(value) {
  return jspb.Message.setField(this, 17, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.addDateRange = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 17, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.clearDateRangeList = function() {
  return this.setDateRangeList([]);
};


/**
 * optional bool with_user = 18;
 * @return {boolean}
 */
proto.ActivityLog.prototype.getWithUser = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 18, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setWithUser = function(value) {
  return jspb.Message.setProto3BooleanField(this, 18, value);
};


/**
 * optional User user = 19;
 * @return {?proto.User}
 */
proto.ActivityLog.prototype.getUser = function() {
  return /** @type{?proto.User} */ (
    jspb.Message.getWrapperField(this, user_pb.User, 19));
};


/**
 * @param {?proto.User|undefined} value
 * @return {!proto.ActivityLog} returns this
*/
proto.ActivityLog.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ActivityLog.prototype.hasUser = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional int32 timeoff_request_id = 20;
 * @return {number}
 */
proto.ActivityLog.prototype.getTimeoffRequestId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setTimeoffRequestId = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional string date_target = 21;
 * @return {string}
 */
proto.ActivityLog.prototype.getDateTarget = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setDateTarget = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * repeated string not_equals = 22;
 * @return {!Array<string>}
 */
proto.ActivityLog.prototype.getNotEqualsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 22));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.setNotEqualsList = function(value) {
  return jspb.Message.setField(this, 22, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.addNotEquals = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 22, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ActivityLog} returns this
 */
proto.ActivityLog.prototype.clearNotEqualsList = function() {
  return this.setNotEqualsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ActivityLogList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ActivityLogList.prototype.toObject = function(opt_includeInstance) {
  return proto.ActivityLogList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ActivityLogList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ActivityLogList.toObject = function(includeInstance, msg) {
  var f, obj = {
    resultsList: jspb.Message.toObjectList(msg.getResultsList(),
    proto.ActivityLog.toObject, includeInstance),
    totalCount: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ActivityLogList}
 */
proto.ActivityLogList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ActivityLogList;
  return proto.ActivityLogList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ActivityLogList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ActivityLogList}
 */
proto.ActivityLogList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ActivityLog;
      reader.readMessage(value,proto.ActivityLog.deserializeBinaryFromReader);
      msg.addResults(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ActivityLogList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ActivityLogList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ActivityLogList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ActivityLogList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.ActivityLog.serializeBinaryToWriter
    );
  }
  f = message.getTotalCount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * repeated ActivityLog results = 1;
 * @return {!Array<!proto.ActivityLog>}
 */
proto.ActivityLogList.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.ActivityLog>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ActivityLog, 1));
};


/**
 * @param {!Array<!proto.ActivityLog>} value
 * @return {!proto.ActivityLogList} returns this
*/
proto.ActivityLogList.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.ActivityLog=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ActivityLog}
 */
proto.ActivityLogList.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.ActivityLog, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ActivityLogList} returns this
 */
proto.ActivityLogList.prototype.clearResultsList = function() {
  return this.setResultsList([]);
};


/**
 * optional int32 total_count = 2;
 * @return {number}
 */
proto.ActivityLogList.prototype.getTotalCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ActivityLogList} returns this
 */
proto.ActivityLogList.prototype.setTotalCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto);
