// source: document.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Document', null, global);
goog.exportSymbol('proto.DocumentList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Document = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Document.repeatedFields_, null);
};
goog.inherits(proto.Document, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Document.displayName = 'proto.Document';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DocumentList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.DocumentList.repeatedFields_, null);
};
goog.inherits(proto.DocumentList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DocumentList.displayName = 'proto.DocumentList';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Document.repeatedFields_ = [17,21];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Document.prototype.toObject = function(opt_includeInstance) {
  return proto.Document.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Document} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Document.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    invoiceId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    propertyId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    contractId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    userId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    taskId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    fileId: jspb.Message.getFieldWithDefault(msg, 7, 0),
    filename: jspb.Message.getFieldWithDefault(msg, 8, ""),
    dateCreated: jspb.Message.getFieldWithDefault(msg, 9, ""),
    description: jspb.Message.getFieldWithDefault(msg, 10, ""),
    type: jspb.Message.getFieldWithDefault(msg, 11, 0),
    version: jspb.Message.getFieldWithDefault(msg, 12, 0),
    invoice: jspb.Message.getFieldWithDefault(msg, 13, 0),
    quote: jspb.Message.getFieldWithDefault(msg, 14, 0),
    maintenance: jspb.Message.getFieldWithDefault(msg, 15, 0),
    other: jspb.Message.getFieldWithDefault(msg, 16, 0),
    fieldMaskList: (f = jspb.Message.getRepeatedField(msg, 17)) == null ? undefined : f,
    pageNumber: jspb.Message.getFieldWithDefault(msg, 18, 0),
    orderBy: jspb.Message.getFieldWithDefault(msg, 19, ""),
    orderDir: jspb.Message.getFieldWithDefault(msg, 20, ""),
    notEqualsList: (f = jspb.Message.getRepeatedField(msg, 21)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Document}
 */
proto.Document.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Document;
  return proto.Document.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Document} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Document}
 */
proto.Document.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInvoiceId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPropertyId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setContractId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUserId(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTaskId(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFileId(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setDateCreated(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setType(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInvoice(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuote(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaintenance(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOther(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.addFieldMask(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageNumber(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderBy(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderDir(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.addNotEquals(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Document.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Document.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Document} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Document.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getInvoiceId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPropertyId();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getContractId();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getUserId();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getTaskId();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getFileId();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDateCreated();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getType();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getInvoice();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getQuote();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getMaintenance();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getOther();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
  f = message.getFieldMaskList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      17,
      f
    );
  }
  f = message.getPageNumber();
  if (f !== 0) {
    writer.writeInt32(
      18,
      f
    );
  }
  f = message.getOrderBy();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getOrderDir();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getNotEqualsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      21,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.Document.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 invoice_id = 2;
 * @return {number}
 */
proto.Document.prototype.getInvoiceId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setInvoiceId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 property_id = 3;
 * @return {number}
 */
proto.Document.prototype.getPropertyId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setPropertyId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 contract_id = 4;
 * @return {number}
 */
proto.Document.prototype.getContractId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setContractId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 user_id = 5;
 * @return {number}
 */
proto.Document.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setUserId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 task_id = 6;
 * @return {number}
 */
proto.Document.prototype.getTaskId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setTaskId = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 file_id = 7;
 * @return {number}
 */
proto.Document.prototype.getFileId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setFileId = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string filename = 8;
 * @return {string}
 */
proto.Document.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string date_created = 9;
 * @return {string}
 */
proto.Document.prototype.getDateCreated = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setDateCreated = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string description = 10;
 * @return {string}
 */
proto.Document.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional int32 type = 11;
 * @return {number}
 */
proto.Document.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setType = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 version = 12;
 * @return {number}
 */
proto.Document.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int32 invoice = 13;
 * @return {number}
 */
proto.Document.prototype.getInvoice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setInvoice = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int32 quote = 14;
 * @return {number}
 */
proto.Document.prototype.getQuote = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setQuote = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 maintenance = 15;
 * @return {number}
 */
proto.Document.prototype.getMaintenance = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setMaintenance = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional int32 other = 16;
 * @return {number}
 */
proto.Document.prototype.getOther = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setOther = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * repeated string field_mask = 17;
 * @return {!Array<string>}
 */
proto.Document.prototype.getFieldMaskList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 17));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setFieldMaskList = function(value) {
  return jspb.Message.setField(this, 17, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.addFieldMask = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 17, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.clearFieldMaskList = function() {
  return this.setFieldMaskList([]);
};


/**
 * optional int32 page_number = 18;
 * @return {number}
 */
proto.Document.prototype.getPageNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setPageNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional string order_by = 19;
 * @return {string}
 */
proto.Document.prototype.getOrderBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setOrderBy = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional string order_dir = 20;
 * @return {string}
 */
proto.Document.prototype.getOrderDir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setOrderDir = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * repeated string not_equals = 21;
 * @return {!Array<string>}
 */
proto.Document.prototype.getNotEqualsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 21));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.setNotEqualsList = function(value) {
  return jspb.Message.setField(this, 21, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.addNotEquals = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 21, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Document} returns this
 */
proto.Document.prototype.clearNotEqualsList = function() {
  return this.setNotEqualsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.DocumentList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DocumentList.prototype.toObject = function(opt_includeInstance) {
  return proto.DocumentList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DocumentList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DocumentList.toObject = function(includeInstance, msg) {
  var f, obj = {
    resultsList: jspb.Message.toObjectList(msg.getResultsList(),
    proto.Document.toObject, includeInstance),
    totalCount: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DocumentList}
 */
proto.DocumentList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DocumentList;
  return proto.DocumentList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DocumentList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DocumentList}
 */
proto.DocumentList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Document;
      reader.readMessage(value,proto.Document.deserializeBinaryFromReader);
      msg.addResults(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DocumentList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DocumentList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DocumentList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DocumentList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.Document.serializeBinaryToWriter
    );
  }
  f = message.getTotalCount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * repeated Document results = 1;
 * @return {!Array<!proto.Document>}
 */
proto.DocumentList.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.Document>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Document, 1));
};


/**
 * @param {!Array<!proto.Document>} value
 * @return {!proto.DocumentList} returns this
*/
proto.DocumentList.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.Document=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Document}
 */
proto.DocumentList.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.Document, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DocumentList} returns this
 */
proto.DocumentList.prototype.clearResultsList = function() {
  return this.setResultsList([]);
};


/**
 * optional int32 total_count = 2;
 * @return {number}
 */
proto.DocumentList.prototype.getTotalCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.DocumentList} returns this
 */
proto.DocumentList.prototype.setTotalCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto);
