// source: system_invoice_type.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.SystemInvoiceType', null, global);
goog.exportSymbol('proto.SystemInvoiceTypeList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SystemInvoiceType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SystemInvoiceType.repeatedFields_, null);
};
goog.inherits(proto.SystemInvoiceType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SystemInvoiceType.displayName = 'proto.SystemInvoiceType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SystemInvoiceTypeList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SystemInvoiceTypeList.repeatedFields_, null);
};
goog.inherits(proto.SystemInvoiceTypeList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SystemInvoiceTypeList.displayName = 'proto.SystemInvoiceTypeList';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SystemInvoiceType.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SystemInvoiceType.prototype.toObject = function(opt_includeInstance) {
  return proto.SystemInvoiceType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SystemInvoiceType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SystemInvoiceType.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    systemReadingTypeId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    reading1: jspb.Message.getFieldWithDefault(msg, 3, ""),
    reading2: jspb.Message.getFieldWithDefault(msg, 4, ""),
    reading3: jspb.Message.getFieldWithDefault(msg, 5, ""),
    reading4: jspb.Message.getFieldWithDefault(msg, 6, ""),
    reading5: jspb.Message.getFieldWithDefault(msg, 7, ""),
    reading6: jspb.Message.getFieldWithDefault(msg, 8, ""),
    reading7: jspb.Message.getFieldWithDefault(msg, 9, ""),
    reading8: jspb.Message.getFieldWithDefault(msg, 10, ""),
    fieldMaskList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    pageNumber: jspb.Message.getFieldWithDefault(msg, 12, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SystemInvoiceType}
 */
proto.SystemInvoiceType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SystemInvoiceType;
  return proto.SystemInvoiceType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SystemInvoiceType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SystemInvoiceType}
 */
proto.SystemInvoiceType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSystemReadingTypeId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setReading1(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setReading2(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setReading3(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setReading4(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setReading5(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setReading6(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setReading7(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setReading8(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addFieldMask(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageNumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SystemInvoiceType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SystemInvoiceType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SystemInvoiceType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SystemInvoiceType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSystemReadingTypeId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getReading1();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getReading2();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getReading3();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getReading4();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getReading5();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getReading6();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getReading7();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getReading8();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getFieldMaskList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getPageNumber();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.SystemInvoiceType.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 system_reading_type_id = 2;
 * @return {number}
 */
proto.SystemInvoiceType.prototype.getSystemReadingTypeId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setSystemReadingTypeId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string reading1 = 3;
 * @return {string}
 */
proto.SystemInvoiceType.prototype.getReading1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setReading1 = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string reading2 = 4;
 * @return {string}
 */
proto.SystemInvoiceType.prototype.getReading2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setReading2 = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string reading3 = 5;
 * @return {string}
 */
proto.SystemInvoiceType.prototype.getReading3 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setReading3 = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string reading4 = 6;
 * @return {string}
 */
proto.SystemInvoiceType.prototype.getReading4 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setReading4 = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string reading5 = 7;
 * @return {string}
 */
proto.SystemInvoiceType.prototype.getReading5 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setReading5 = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string reading6 = 8;
 * @return {string}
 */
proto.SystemInvoiceType.prototype.getReading6 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setReading6 = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string reading7 = 9;
 * @return {string}
 */
proto.SystemInvoiceType.prototype.getReading7 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setReading7 = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string reading8 = 10;
 * @return {string}
 */
proto.SystemInvoiceType.prototype.getReading8 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setReading8 = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * repeated string field_mask = 11;
 * @return {!Array<string>}
 */
proto.SystemInvoiceType.prototype.getFieldMaskList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setFieldMaskList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.addFieldMask = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.clearFieldMaskList = function() {
  return this.setFieldMaskList([]);
};


/**
 * optional int32 page_number = 12;
 * @return {number}
 */
proto.SystemInvoiceType.prototype.getPageNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.SystemInvoiceType} returns this
 */
proto.SystemInvoiceType.prototype.setPageNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SystemInvoiceTypeList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SystemInvoiceTypeList.prototype.toObject = function(opt_includeInstance) {
  return proto.SystemInvoiceTypeList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SystemInvoiceTypeList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SystemInvoiceTypeList.toObject = function(includeInstance, msg) {
  var f, obj = {
    resultsList: jspb.Message.toObjectList(msg.getResultsList(),
    proto.SystemInvoiceType.toObject, includeInstance),
    totalCount: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SystemInvoiceTypeList}
 */
proto.SystemInvoiceTypeList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SystemInvoiceTypeList;
  return proto.SystemInvoiceTypeList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SystemInvoiceTypeList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SystemInvoiceTypeList}
 */
proto.SystemInvoiceTypeList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.SystemInvoiceType;
      reader.readMessage(value,proto.SystemInvoiceType.deserializeBinaryFromReader);
      msg.addResults(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SystemInvoiceTypeList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SystemInvoiceTypeList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SystemInvoiceTypeList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SystemInvoiceTypeList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.SystemInvoiceType.serializeBinaryToWriter
    );
  }
  f = message.getTotalCount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * repeated SystemInvoiceType results = 1;
 * @return {!Array<!proto.SystemInvoiceType>}
 */
proto.SystemInvoiceTypeList.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.SystemInvoiceType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SystemInvoiceType, 1));
};


/**
 * @param {!Array<!proto.SystemInvoiceType>} value
 * @return {!proto.SystemInvoiceTypeList} returns this
*/
proto.SystemInvoiceTypeList.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.SystemInvoiceType=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SystemInvoiceType}
 */
proto.SystemInvoiceTypeList.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.SystemInvoiceType, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SystemInvoiceTypeList} returns this
 */
proto.SystemInvoiceTypeList.prototype.clearResultsList = function() {
  return this.setResultsList([]);
};


/**
 * optional int32 total_count = 2;
 * @return {number}
 */
proto.SystemInvoiceTypeList.prototype.getTotalCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SystemInvoiceTypeList} returns this
 */
proto.SystemInvoiceTypeList.prototype.setTotalCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto);
