export default {
  id: 104483,
  externalId: 101253,
  externalCode: 'user',
  referenceNumber: '13541',
  creatorUserId: 101253,
  timeCreated: '2020-05-05 19:21:00',
  timeDue: '2020-05-05 19:21:00',
  briefDescription: '33322',
  details: '',
  notes: '',
  statusId: 1,
  priorityId: 2,
  referenceUrl: 'http://test.com',
  isActive: 1,
  billable: 0,
  billableType: 'Spiff',
  flatRate: 0,
  hourlyStart: '',
  hourlyEnd: '',
  address: '',
  orderNum: '',
  spiffAmount: 2,
  spiffJobNumber: '18-70336-ACW',
  spiffTypeId: 1,
  spiffAddress: 'Flat street',
  toolpurchaseDate: '2020-05-05 19:21:00',
  toolpurchaseCost: 0,
  toolpurchaseFile: '',
  adminActionId: 0,
  datePerformed: '2020-05-12 19:21:00',
  spiffToolId: '816352',
  spiffToolCloseoutDate: '',
  fieldMaskList: [],
  pageNumber: 0,
  dateRangeList: [],
  dateTargetList: [],
  event: {
    id: 70336,
    propertyId: 1763,
    customerId: 90,
    contractId: 0,
    contractNumber: '',
    logJobNumber: '18-70336-ACW',
  },
  ownerName: 'Krzysztof Olbinski',
  actionsList: [
    {
      id: 7665,
      taskId: 104483,
      reviewedBy: 'n',
      status: 1,
      reason: '',
      decisionDate: '2020-05-05 00:00:00',
      createdDate: '2020-05-06 01:48:31',
      grantedDate: '',
      revokedDate: '',
      fieldMaskList: [],
      pageNumber: 0,
      orderBy: '',
      orderDir: '',
      dateRangeList: [],
      dateTargetList: [],
    },
    {
      id: 7663,
      taskId: 104483,
      reviewedBy: 's',
      status: 2,
      reason: 's',
      decisionDate: '2020-05-05 00:00:00',
      createdDate: '2020-05-06 01:19:10',
      grantedDate: '',
      revokedDate: '',
      fieldMaskList: [],
      pageNumber: 0,
      orderBy: '',
      orderDir: '',
      dateRangeList: [],
      dateTargetList: [],
    },
    {
      id: 7661,
      taskId: 104483,
      reviewedBy: 'a',
      status: 3,
      reason: '',
      decisionDate: '2020-05-05 00:00:00',
      createdDate: '2020-05-06 01:08:09',
      grantedDate: '',
      revokedDate: '',
      fieldMaskList: [],
      pageNumber: 0,
      orderBy: '',
      orderDir: '',
      dateRangeList: [],
      dateTargetList: [],
    },
  ],
  referenceAction: {
    id: 0,
    taskId: 104483,
    reviewedBy: '',
    status: 0,
    reason: '',
    decisionDate: '',
    createdDate: '',
    grantedDate: '',
    revokedDate: '',
    fieldMaskList: [],
    pageNumber: 0,
    orderBy: 'created_date',
    orderDir: 'desc',
    dateRangeList: [],
    dateTargetList: [],
  },
  orderBy: '',
  orderDir: '',
  duplicatesList: [
    {
      id: 8575,
      spiffTypeId: 2,
      timeDue: '2018-03-31 00:00:00',
      ownerName: 'Ricardo Ocando',
      actionsList: [
        {
          id: 2756,
          taskId: 8575,
          reviewedBy: 'mike k',
          status: 1,
          reason: '',
          decisionDate: '2018-04-12 00:00:00',
          createdDate: '2018-04-12 22:58:54',
          grantedDate: '',
          revokedDate: '',
          fieldMaskList: [],
          pageNumber: 0,
          orderBy: '',
          orderDir: '',
          dateRangeList: [],
          dateTargetList: [],
        },
      ],
    },
    {
      id: 8584,
      spiffTypeId: 2,
      timeDue: '2018-04-02 00:00:00',
      ownerName: 'Kervince Labbe',
      actionsList: [
        {
          id: 2755,
          taskId: 8584,
          reviewedBy: 'mike k',
          status: 1,
          reason: '',
          decisionDate: '2018-04-12 00:00:00',
          createdDate: '2018-04-12 22:54:28',
          grantedDate: '',
          revokedDate: '',
          fieldMaskList: [],
          pageNumber: 0,
          orderBy: '',
          orderDir: '',
          dateRangeList: [],
          dateTargetList: [],
        },
      ],
    },
    {
      id: 8586,
      spiffTypeId: 1,
      timeDue: '2018-04-03 00:00:00',
      ownerName: 'Meuse Israel',
      actionsList: [
        {
          id: 2754,
          taskId: 8586,
          reviewedBy: 'mike k',
          status: 1,
          reason: '',
          decisionDate: '2018-04-12 00:00:00',
          createdDate: '2018-04-12 22:53:19',
          grantedDate: '',
          revokedDate: '',
          fieldMaskList: [],
          pageNumber: 0,
          orderBy: '',
          orderDir: '',
          dateRangeList: [],
          dateTargetList: [],
        },
      ],
    },
    {
      id: 104464,
      spiffTypeId: 1,
      timeDue: '2020-05-01 16:06:00',
      ownerName: 'Krzysztof Olbinski',
      actionsList: [
        {
          id: 7625,
          taskId: 104464,
          reviewedBy: 'www',
          status: 1,
          reason: 'wwwwww',
          decisionDate: '2020-05-04 00:00:00',
          createdDate: '2020-05-04 23:16:00',
          grantedDate: '',
          revokedDate: '',
          fieldMaskList: [],
          pageNumber: 0,
          orderBy: '',
          orderDir: '',
          dateRangeList: [],
          dateTargetList: [],
        },
        {
          id: 7620,
          taskId: 104464,
          reviewedBy: 'aaa',
          status: 1,
          reason: 'bbb',
          decisionDate: '2020-05-02 00:00:00',
          createdDate: '2020-05-04 21:02:00',
          grantedDate: '',
          revokedDate: '',
          fieldMaskList: [],
          pageNumber: 0,
          orderBy: '',
          orderDir: '',
          dateRangeList: [],
          dateTargetList: [],
        },
        {
          id: 7621,
          taskId: 104464,
          reviewedBy: 'bb',
          status: 2,
          reason: 'bb',
          decisionDate: '2020-05-06 00:00:00',
          createdDate: '2020-05-04 21:02:00',
          grantedDate: '',
          revokedDate: '',
          fieldMaskList: [],
          pageNumber: 0,
          orderBy: '',
          orderDir: '',
          dateRangeList: [],
          dateTargetList: [],
        },
        {
          id: 7622,
          taskId: 104464,
          reviewedBy: 'cc',
          status: 3,
          reason: 'cc',
          decisionDate: '2020-05-08 00:00:00',
          createdDate: '2020-05-04 21:02:00',
          grantedDate: '',
          revokedDate: '',
          fieldMaskList: [],
          pageNumber: 0,
          orderBy: '',
          orderDir: '',
          dateRangeList: [],
          dateTargetList: [],
        },
        {
          id: 7623,
          taskId: 104464,
          reviewedBy: 'dd',
          status: 1,
          reason: 'dd',
          decisionDate: '2020-05-04 00:00:00',
          createdDate: '2020-05-04 21:02:00',
          grantedDate: '',
          revokedDate: '',
          fieldMaskList: [],
          pageNumber: 0,
          orderBy: '',
          orderDir: '',
          dateRangeList: [],
          dateTargetList: [],
        },
      ],
    },
    {
      id: 104467,
      spiffTypeId: 1,
      timeDue: '2020-05-01 16:35:00',
      ownerName: 'Krzysztof Olbinski',
      actionsList: [],
    },
  ],
};
