export default {
  id: 104456,
  eventId: 104456,
  externalId: 101253,
  externalCode: 'user',
  referenceNumber: '',
  creatorUserId: 0,
  timeCreated: '2020-04-30 19:08:00',
  timeDue: '2020-04-30 19:08:00',
  briefDescription: 'dd',
  details: '',
  notes: '',
  statusId: 1,
  priorityId: 2,
  referenceUrl: '',
  isActive: true,
  billable: 0,
  billableType: 'Tool Purchase',
  flatRate: 0,
  hourlyStart: '',
  hourlyEnd: '',
  address: '',
  orderNum: '',
  spiffAmount: 0,
  spiffJobNumber: '11',
  spiffTypeId: 0,
  spiffAddress: '',
  toolpurchaseDate: '2020-05-07 19:08:00',
  toolpurchaseCost: 10,
  toolpurchaseFile: '',
  adminActionId: 0,
  datePerformed: '2020-04-30 19:08:00',
  spiffToolId: 'TFD-2004-003',
  spiffToolCloseoutDate: '',
  fieldMaskList: [],
  pageNumber: 0,
  dateRangeList: [],
  dateTargetList: [],
  event: {
    id: 0,
    propertyId: 0,
    customerId: 0,
    contractId: 0,
    contractNumber: '',
    logJobNumber: '',
  },
  ownerName: 'Krzysztof Olbinski',
  actionsList: [
    {
      id: 7619,
      taskId: 104456,
      reviewedBy: 'fwfew',
      status: 1,
      reason: 'vberbr few fe',
      decisionDate: '2020-04-30 00:00:00',
      createdDate: '2020-05-01 01:13:00',
      grantedDate: '',
      revokedDate: '',
      fieldMaskList: [],
      pageNumber: 0,
      orderBy: '',
      orderDir: '',
      dateRangeList: [],
      dateTargetList: [],
    },
    {
      id: 7618,
      taskId: 104456,
      reviewedBy: 'fewfwq',
      status: 3,
      reason: 'cvevewvew few',
      decisionDate: '2020-04-30 00:00:00',
      createdDate: '2020-04-30 19:13:19',
      grantedDate: '',
      revokedDate: '',
      fieldMaskList: [],
      pageNumber: 0,
      orderBy: '',
      orderDir: '',
      dateRangeList: [],
      dateTargetList: [],
    },
  ],
  referenceAction: {
    id: 0,
    taskId: 104456,
    reviewedBy: '',
    status: 0,
    reason: '',
    decisionDate: '',
    createdDate: '',
    grantedDate: '',
    revokedDate: '',
    fieldMaskList: [],
    pageNumber: 0,
    orderBy: 'created_date',
    orderDir: 'desc',
    dateRangeList: [],
    dateTargetList: [],
  },
  orderBy: '',
  orderDir: '',
  duplicatesList: [],
};
